<?php
/**
 * JellyStream Database Helper
 * Direct SQLite database access
 */

class Database {
    private $pdo;

    public function __construct($db_path = DB_PATH) {
        try {
            $this->pdo = new PDO('sqlite:' . $db_path);
            $this->pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            $this->pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
        } catch (PDOException $e) {
            die("Database connection failed: " . $e->getMessage());
        }
    }

    /**
     * Execute SELECT query
     */
    public function query($sql, $params = []) {
        try {
            $stmt = $this->pdo->prepare($sql);
            $stmt->execute($params);
            return $stmt->fetchAll();
        } catch (PDOException $e) {
            error_log("Database query error: " . $e->getMessage());
            return false;
        }
    }

    /**
     * Execute INSERT, UPDATE, DELETE
     */
    public function execute($sql, $params = []) {
        try {
            $stmt = $this->pdo->prepare($sql);
            return $stmt->execute($params);
        } catch (PDOException $e) {
            error_log("Database execute error: " . $e->getMessage());
            return false;
        }
    }

    /**
     * Get last insert ID
     */
    public function lastInsertId() {
        return $this->pdo->lastInsertId();
    }

    /**
     * Get all streams
     */
    public function getStreams() {
        return $this->query("SELECT * FROM streams ORDER BY created_at DESC");
    }

    /**
     * Get stream by ID
     */
    public function getStream($id) {
        $result = $this->query("SELECT * FROM streams WHERE id = ?", [$id]);
        return $result ? $result[0] : null;
    }

    /**
     * Get all schedules
     */
    public function getSchedules($stream_id = null) {
        if ($stream_id) {
            return $this->query(
                "SELECT * FROM schedules WHERE stream_id = ? ORDER BY scheduled_time ASC",
                [$stream_id]
            );
        }
        return $this->query("SELECT * FROM schedules ORDER BY scheduled_time ASC");
    }

    /**
     * Read configuration from .env file
     */
    public function getEnvConfig() {
        $env_file = __DIR__ . '/../../../../.env';
        $config = [];

        if (file_exists($env_file)) {
            $lines = file($env_file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
            foreach ($lines as $line) {
                if (strpos($line, '#') === 0) continue;
                if (strpos($line, '=') === false) continue;

                list($key, $value) = explode('=', $line, 2);
                $config[trim($key)] = trim($value);
            }
        }

        return $config;
    }

    /**
     * Write configuration to .env file
     */
    public function saveEnvConfig($config) {
        $env_file = __DIR__ . '/../../../../.env';
        $lines = [];

        $lines[] = "# JellyStream Configuration";
        $lines[] = "# Auto-generated by setup wizard";
        $lines[] = "";

        foreach ($config as $key => $value) {
            $lines[] = "{$key}={$value}";
        }

        return file_put_contents($env_file, implode("\n", $lines));
    }
}
